### ISSUE TITLE
systemd service scripts for InfluxDB

### ISSUE THREAD

**Issue by shantanoo-desai** [C-X1/meta-influx#10]
Is it worth putting in `systemd` scripts for __InfluxDB__ within the `scripts` directory?

perhaps it might be a preference for those who use the repository to have influxdb start on boot for their embedded systems.

**Comment by nefethael** [comment]
@shantanoo-desai If you only need influxdb with systemd I made a recipe [here](https://github.com/nefethael/meta-random/commit/079eda48c0d98386fb90c90b4dcfd3b5a741e947)

**Comment by shantanoo-desai** [comment]
@nefethael hi does your meta layer have recipe for how to use the new version of InfluxDB in Yocto?

**Comment by nefethael** [comment]
@shantanoo-desai This layer is not intended to be added as-if in Yocto, but you can copy "recipes-dbs/influxdb" folder to your own layer and add github.com-influxdata-influxdb to your image.

**Comment by shantanoo-desai** [comment]
@nefethael does one need to install the go binary on the machine in order to bake the recipe? and if so, where do I mention the path in the recipe so that the influxdb code.

**Comment by nefethael** [comment]
@shantanoo-desai you don't need anything more, everything is taking care by `inherit go`, so bitbake will compile go in target environment and add it automatically. BTW you can contact me at vincent.prince.fr[at]gmail.com.
